name: RTL Verification CI

on:
  push:
    branches: [ "main", "feature-can-bus" ]
  pull_request:
    branches: [ "main" ]

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Tools (Icarus & Verilator)
      run: |
              sudo apt-get update
              sudo apt-get install -y iverilog verilator
    
    - name: Run Distributed Math Network Testbench
      working-directory: ./can_bus
      run: make
